openapi: 3.1.0
info:
  title: AFM Access Profiles Health API
  version: 0.1.0
tags:
- name: Health
paths:
  /api/health:
    get:
      summary: Health
      operationId: health_api_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Health
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
